### ISSUE TITLE
blockstack install naming

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-dashboard#119]
We need to come up with a descriptive name of the Blockstack Install.

So far, @shea256 and myself have come up with;
1. Browser Add-on
1. Browser Plugin
1. Browser Extension
1. Browser Portal

**Comment by guylepage3** [comment]
I really like **4. Browser Portal**

**Comment by guylepage3** [comment]
Another is;
- Browser Gateway

**Comment by shea256** [comment]
I like Browser Portal and Browser Upgrade

**Comment by guylepage3** [comment]
>I like Browser Portal and Browser Upgrade

I like Portal as well. Browser Upgrade is a bit confusing as to what it is. Is it an upgrade of my actual browser? What exactly is being upgraded?

**Comment by shea256** [comment]
@muneeb-ali like's Browser Upgrade.

I also actually like Browser Addon too.

**Comment by guylepage3** [comment]
> @muneeb-ali like's Browser Upgrade.

What is it though? I have no idea what that means. Also, this would sound weird...

> Upgrade your Blockstack Browser Upgrade to version 14.0.

**Comment by muneeb-ali** [comment]
We could also just say that "install Blockstack". There is just one installer. It gives them the CLI, Core, and the browser extensions.

**Comment by shea256** [comment]
Yeah that's an option.

But in that case, to clarify, we're then using the term "browser extension" for the browser component.

**Comment by guylepage3** [comment]
>We could also just say that "install Blockstack". There is just one installer. It gives them the CLI, Core, and the browser extensions.

I really like the idea that it's just the **Blockstack Installer**. It's simple. But it's not very descriptive. Can't seem to find something better than **Portal**.

**Comment by guylepage3** [comment]
Moved to... https://forum.blockstack.org/t/naming-the-blockstack-installer/408
